-- 订单表添加退款和纠纷相关字段
ALTER TABLE `order`
ADD COLUMN `refund_status` VARCHAR(20) DEFAULT NULL COMMENT '退款状态: NONE, APPLYING, APPROVED, REJECTED',
ADD COLUMN `refund_reason` VARCHAR(500) DEFAULT NULL COMMENT '退款原因',
ADD COLUMN `refund_time` DATETIME DEFAULT NULL COMMENT '退款时间',
ADD COLUMN `dispute_status` VARCHAR(20) DEFAULT NULL COMMENT '纠纷状态: NONE, APPLYING, PROCESSING, RESOLVED',
ADD COLUMN `dispute_reason` VARCHAR(500) DEFAULT NULL COMMENT '纠纷原因',
ADD COLUMN `dispute_evidence` TEXT DEFAULT NULL COMMENT '纠纷证据',
ADD COLUMN `dispute_result` VARCHAR(500) DEFAULT NULL COMMENT '纠纷处理结果',
ADD COLUMN `dispute_time` DATETIME DEFAULT NULL COMMENT '申诉时间',
ADD COLUMN `resolve_time` DATETIME DEFAULT NULL COMMENT '解决时间';

-- 订单状态添加 COMPLETED 用于表示订单已完成
-- 退款状态: NONE(无退款), APPLYING(申请中), APPROVED(已同意), REJECTED(已拒绝)
-- 纠纷状态: NONE(无纠纷), APPLYING(申诉中), PROCESSING(处理中), RESOLVED(已解决)
